controller_manager:
  ros__parameters:
    controller_manager_timeout: 10.0
    joint_group_effort_controller_go2_1:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_states_controller_go2_1:
      type: joint_state_broadcaster/JointStateBroadcaster
    update_rate: 250
    use_sim_time: true

joint_group_effort_controller_go2_1:
  ros__parameters:
    action_monitor_rate: 20.0
    action_tolerance: 1.0
    allow_partial_joints_goal: true
    command_interfaces:
    - effort
    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.01
    gains:
      go2_1/lf_hip_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/lf_lower_leg_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/lf_upper_leg_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/lh_hip_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/lh_lower_leg_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/lh_upper_leg_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/rf_hip_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/rf_lower_leg_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/rf_upper_leg_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/rh_hip_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/rh_lower_leg_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
      go2_1/rh_upper_leg_joint:
        d: 1.0
        i: 0.2
        i_clamp: 2.5
        p: 100.0
    hold_trajectory_duration: 0.0
    joints:
    - go2_1/lf_hip_joint
    - go2_1/lf_upper_leg_joint
    - go2_1/lf_lower_leg_joint
    - go2_1/rf_hip_joint
    - go2_1/rf_upper_leg_joint
    - go2_1/rf_lower_leg_joint
    - go2_1/lh_hip_joint
    - go2_1/lh_upper_leg_joint
    - go2_1/lh_lower_leg_joint
    - go2_1/rh_hip_joint
    - go2_1/rh_upper_leg_joint
    - go2_1/rh_lower_leg_joint
    state_interfaces:
    - position
    - velocity
    state_publish_rate: 100.0
    use_sim_time: true

joint_states_controller_go2_1:
  ros__parameters:
    use_sim_time: true